name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: DockerEnv
    steps:
    - uses: actions/checkout@v3    
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
    - name: Make build script executable
      run: chmod +x ./build.sh
    - name: Publish Docker
      run: ./build.sh PublishDocker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
